const styles = StyleSheet.create({
  container: { flex: 1, width: '100%' },
  scrollContent: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 24 },
  card: { width: '100%', maxWidth: 380, borderRadius: 12, borderWidth: 1, padding: 20 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  heading: { fontSize: 20, fontWeight: '700' },
  backBtn: { fontSize: 14, fontWeight: '500' },
  form: { gap: 8 },
  row: { flexDirection: 'row', gap: 8 },
  half: { flex: 1 },
  label: { fontSize: 14, fontWeight: '500', marginBottom: 4 },
  input: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, fontSize: 14, marginBottom: 8 },
  button: { borderRadius: 8, paddingVertical: 12, alignItems: 'center', marginTop: 8 },
  buttonText: { fontSize: 16, fontWeight: '600' },
  alert: { borderRadius: 8, padding: 12, marginBottom: 8 },
  errorText: { fontSize: 13, marginBottom: 2 },
  successTitle: { fontSize: 14, fontWeight: '600', marginBottom: 4 },
  successText: { fontSize: 12 },
});